# Book Recommendation System

- import libraries

In [55]:
import pandas as pd
import numpy as np
import seaborn as sns

- load dataset

In [56]:
books = pd.read_csv("Books.csv")
users = pd.read_csv("Users.csv")
ratings = pd.read_csv("Ratings.csv")

C:\Users\azhar\AppData\Local\Temp\ipykernel_12376\2906776592.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

- find shape of data

In [57]:

books.shape

(271360, 8)

In [58]:
users.shape

(278858, 3)

In [59]:
ratings.shape

(1048575, 3)

- find nan values

In [60]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

- drop unwanted columns

In [61]:
users = users.drop(columns="Age")

In [62]:
users.describe()

            User-ID
count  278858.00000
mean   139429.50000
std     80499.51502
min         1.00000
25%     69715.25000
50%    139429.50000
75%    209143.75000
max    278858.00000

- find and drop duplicates

In [63]:
ratings.duplicated().sum()

72

In [64]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726   155061224            5
2   276727   446520802            0
3   276729  052165615X            3
4   276729   521795028            6

In [65]:
ratings.drop_duplicates(inplace=True)

In [66]:
ratings.describe()

            User-ID   Book-Rating
count  1.048503e+06  1.048503e+06
mean   1.285092e+05  2.879937e+00
std    7.421821e+04  3.857874e+00
min    2.000000e+00  0.000000e+00
25%    6.339400e+04  0.000000e+00
50%    1.288350e+05  0.000000e+00
75%    1.927765e+05  7.000000e+00
max    2.788540e+05  1.000000e+01

- merge books and ratings data on ISBN

In [67]:
book_ratings = ratings.merge(books,on="ISBN")

In [68]:
book_ratings.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [69]:
book_ratings.shape

(941105, 10)

In [70]:
book_ratings["Book-Rating"].unique()

array([ 0,  5,  9,  8,  6,  7,  4, 10,  3,  2,  1], dtype=int64)

In [71]:
book_ratings.duplicated().sum()

0

- the code is counting the number of occurrences of each title in the "Book-Title" column of the book_ratings DataFrame, and returning the count of ratings for each title in the "Book-Rating" column

In [72]:
num_of_ratings = book_ratings.groupby(["Book-Title"]).count()["Book-Rating"].reset_index()
num_of_ratings.rename(columns={"Book-Rating":"num-ratings"}, inplace=True)

In [73]:
num_of_ratings.head(15)

                                           Book-Title  num-ratings
0    A Light in the Storm: The Civil War Diary of ...            4
1                               Always Have Popsicles            1
2                Apple Magic (The Collector's series)            1
3    Beyond IBM: Leadership Marketing and Finance ...            1
4    Clifford Visita El Hospital (Clifford El Gran...            1
5                                        Dark Justice            1
6                                            Deceived            2
7    Earth Prayers From around the World: 365 Pray...            9
8    Final Fantasy Anthology: Official Strategy Gu...            4
9    Flight of Fancy: American Heiresses (Zebra Ba...            2
10   Garfield Bigger and Better (Garfield (Numbere...            2
11                          God's Little Promise Book            2
12   Good Wives: Image and Reality in the Lives of...           10
13   Goosebumps Monster Edition 1: Welcome to Dead...            8
14   Harry Potter and the Bible: The Menace Behind...            1

.com- the code is counting the number of occurrences of each title in the "Book-Title" column of the book_ratings DataFrame, and returning the mean of ratings for each title in the "Book-Rating" column

In [74]:
avg_ratings = book_ratings.groupby(["Book-Title"]).mean()["Book-Rating"].reset_index()
avg_ratings.rename(columns={"Book-Rating":"avg-ratings"}, inplace=True)

In [75]:
avg_ratings.head()

                                          Book-Title  avg-ratings
0   A Light in the Storm: The Civil War Diary of ...         2.25
1                              Always Have Popsicles         0.00
2               Apple Magic (The Collector's series)         0.00
3   Beyond IBM: Leadership Marketing and Finance ...         0.00
4   Clifford Visita El Hospital (Clifford El Gran...         0.00

- merge num_of_ratings columns and avg_ratings on Book_Title

In [76]:
popular_df = num_of_ratings.merge(avg_ratings,on='Book-Title')

In [77]:
popular_df

,Book-Title,num-ratings,avg-ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.25
1,Always Have Popsicles,1,0.00
2,Apple Magic (The Collector's series),1,0.00
3,Beyond IBM: Leadership Marketing and Finance ...,1,0.00
4,Clifford Visita El Hospital (Clifford El Gran...,1,0.00
...,...,...,...
230215,Ã?Â?l- Connection.,1,0.00
230216,Ã?Â?lpiraten.,2,0.00
230217,Ã?Â?rger mit Produkt X. Roman.,4,5.25
230218,Ã?Â?stlich der Berge.,2,4.00
230219,Ã?Â?thique en toc,2,4.00

- separate book_ratings which have more than 250 ratings

In [78]:
popular_books= popular_df[popular_df["num-ratings"]>=250].sort_values('avg-ratings', ascending=False).head(50)

In [79]:
popular_books.head(50)

,Book-Title,num-ratings,avg-ratings
76831,Harry Potter and the Goblet of Fire (Book 4),346,5.945087
76843,Harry Potter and the Prisoner of Azkaban (Book 3),380,5.884211
76835,Harry Potter and the Order of the Phoenix (Boo...,316,5.544304
76823,Harry Potter and the Chamber of Secrets (Book 2),501,5.177645
182892,The Hobbit : The Enchanting Prelude to The Lor...,261,4.969349
76854,Harry Potter and the Sorcerer's Stone (Harry P...,519,4.938343
178857,The Fellowship of the Ring (The Lord of the Ri...,340,4.885294
209806,To Kill a Mockingbird,463,4.684665
175236,The Da Vinci Code,828,4.679952
172364,The Catcher in the Rye,401,4.615960
197170,The Secret Life of Bees,704,4.558239
179343,The Five People You Meet in Heaven,392,4.543367
187414,The Lovely Bones: A Novel,1164,4.457045
727,1984,259,4.393822
182870,The Hitchhiker's Guide to the Galaxy,252,4.361111
161045,Stupid White Men ...and Other Sorry Excuses fo...,264,4.337121
195141,The Red Tent (Bestselling Backlist),668,4.326347
213071,"Tuesdays with Morrie: An Old Man, a Young Man,...",437,4.274600
123501,Nickel and Dimed: On (Not) Getting By in America,303,4.244224
61070,Fahrenheit 451,372,4.239247
71407,Girl with a Pearl Earring,486,4.197531
62081,Fast Food Nation: The Dark Side of the All-Ame...,285,4.133333
72927,Good in Bed,456,4.127193
129957,Outlander,262,4.087786
222878,Where the Heart Is (Oprah's Book Club (Paperba...,527,4.070209
148937,Seabiscuit: An American Legend,257,4.066148
168806,The Bean Trees,365,4.032877
103091,Life of Pi,597,4.015075
101002,Left Behind: A Novel of the Earth's Last Days ...,296,3.972973
173443,The Color Purple,289,3.972318
8101,ANGELA'S ASHES,253,3.964427
154258,Skipping Christmas,292,3.934932
180928,"The Golden Compass (His Dark Materials, Book 1)",302,3.927152
12160,American Gods,271,3.896679
209426,Timeline,512,3.857422
150884,Seven Up (A Stephanie Plum Novel),255,3.827451
76493,Hard Eight : A Stephanie Plum Novel (A Stephan...,252,3.821429
5439,A Prayer for Owen Meany,380,3.818421
13783,Angels &amp; Demons,616,3.788961
223339,White Oleander : A Novel (Oprah's Book Club),327,3.785933
202490,"The Vampire Lestat (Vampire Chronicles, Book II)",271,3.756458
162364,Suzanne's Diary for Nicholas,413,3.738499
112883,Me Talk Pretty One Day,426,3.727700
128390,One for the Money (Stephanie Plum Novels (Pape...,269,3.706320
224193,Wicked: The Life and Times of the Wicked Witch...,286,3.678322
20807,Bel Canto: A Novel,319,3.664577
37146,Confessions of a Shopaholic (Summer Display Op...,312,3.663462
115637,Misery,260,3.646154
193383,The Poisonwood Bible: A Novel,455,3.639560
57551,Empire Falls,368,3.635870

In [80]:
popular_books.shape

(50, 3)

In [81]:
- merge books with popular books to get image url of books

SyntaxError: invalid syntax (2387018610.py, line 1)

In [ ]:
popular_books = popular_books.merge(books,on="Book-Title").drop_duplicates("Book-Title")[['Book-Title',"Book-Author",'Image-URL-M','num-ratings',"avg-ratings"]]

In [ ]:
popular_books.shape

(50, 5)

# collabrative filtering based recommender system

- take users which provide ratings on >= 2oo books

In [ ]:
x= book_ratings.groupby("User-ID").count()["Book-Rating"]>200

In [ ]:
book_ratings.shape

(941105, 10)

In [ ]:
x.shape

(83643,)

In [ ]:
literate = x[x].index

In [ ]:
filtered_ratings = book_ratings[book_ratings["User-ID"].isin(literate)]

  - take books which have atleast 50 or more ratings

In [ ]:
y= book_ratings.groupby("Book-Title").count()["Book-Rating"]>50

In [ ]:
famous_books= y[y].index

In [ ]:
final = filtered_ratings[filtered_ratings["Book-Title"].isin(famous_books)]

In [ ]:
final.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
940818,250405,399144781,0,Southern Cross,Patricia Daniels Cornwell,1999,Putnam Pub Group,http://images.amazon.com/images/P/0399144781.0...,http://images.amazon.com/images/P/0399144781.0...,http://images.amazon.com/images/P/0399144781.0...
940819,250405,399150684,0,Naked Prey,John Sandford,2003,Putnam Berkley Audio,http://images.amazon.com/images/P/0399150684.0...,http://images.amazon.com/images/P/0399150684.0...,http://images.amazon.com/images/P/0399150684.0...
940831,250405,553474359,0,In the Presence of the Enemy,Elizabeth George,1996,Random House Audio,http://images.amazon.com/images/P/0553474359.0...,http://images.amazon.com/images/P/0553474359.0...,http://images.amazon.com/images/P/0553474359.0...
940840,250405,679445633,0,A Place Called Freedom,Ken Follett,1995,Random House,http://images.amazon.com/images/P/0679445633.0...,http://images.amazon.com/images/P/0679445633.0...,http://images.amazon.com/images/P/0679445633.0...
940898,250405,1558002650,0,Memories of Midnight,Sidney Sheldon,1990,Audio Literature,http://images.amazon.com/images/P/1558002650.0...,http://images.amazon.com/images/P/1558002650.0...,http://images.amazon.com/images/P/1558002650.0...

### now make pivot table

In [ ]:
pt= final.pivot_table(index= "Book-Title" ,columns="User-ID", values="Book-Rating")

In [ ]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,249111,249628,249862,249894,250184,250405,250764,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16 Lighthouse Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Young Wives,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pt.fillna(0, inplace=True)

In [ ]:
pt.tail(90)

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,249111,249628,249862,249894,250184,250405,250764,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
Vertical Run,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0
Vinegar Hill (Oprah's Book Club (Paperback)),0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Violets Are Blue,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Violin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Visions of Sugar Plums,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Young Wives,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
- calculating similarity between users is to compute the cosine similarity between their rating vectors.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity_score= cosine_similarity(pt)

In [ ]:
similarity_score.shape

(2131, 2131)

In [ ]:
define

-  Python function that recommends similar books based on a book name provided as an input parameter.

In [ ]:
def recommend(book_name):
    index= np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])),key=lambda x:x[1], reverse=True)[1:6]
    data = []
    for i in similar_items:
        items = []
        temp_df = books[books["Book-Title"]==pt.index[i[0]]]
        items.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Title"].values))
        items.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Author"].values))
        items.extend(list(temp_df.drop_duplicates("Book-Title")["Image-URL-M"].values))

        data.append(items)

    return data

In [ ]:
- Now see the results,

In [ ]:
recommend("1984")

[['Lying Awake',
  'Mark Salzman',
  'http://images.amazon.com/images/P/0375406328.01.MZZZZZZZ.jpg'],
 ["The Restaurant at the End of the Universe (Hitchhiker's Trilogy (Paperback))",
  'Douglas Adams',
  'http://images.amazon.com/images/P/0345391810.01.MZZZZZZZ.jpg'],
 ['Waiting',
  'Frank M. Robinson',
  'http://images.amazon.com/images/P/0812541642.01.MZZZZZZZ.jpg'],
 ['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
  'Kurt Vonnegut',
  'http://images.amazon.com/images/P/0440180295.01.MZZZZZZZ.jpg']]

In [ ]:
popular_books["Image-URL-M"][0]

'http://images.amazon.com/images/P/0439139597.01.MZZZZZZZ.jpg'

In [ ]:
import pickle
pickle.dump(popular_books,open("popular.pkl","wb"))

In [ ]:
with open('popular.pkl', 'rb') as file:
    data = pickle.load(file)

In [ ]:
import pickle

with open('popular.pkl', 'rb') as f:
    data = pickle.load(f)

In [ ]:
popular_books

,Book-Title,Book-Author,Image-URL-M,num-ratings,avg-ratings
0,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,346,5.945087
2,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,380,5.884211
5,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,316,5.544304
9,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,501,5.177645
12,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,261,4.969349
13,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,519,4.938343
15,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,340,4.885294
24,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,463,4.684665
32,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,828,4.679952
38,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,401,4.615960
45,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,704,4.558239
51,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,392,4.543367
53,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1164,4.457045
54,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,259,4.393822
65,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,252,4.361111
74,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,264,4.337121
75,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,668,4.326347
76,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,437,4.274600
79,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,303,4.244224
81,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,372,4.239247
94,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,486,4.197531
95,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,285,4.133333
96,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,456,4.127193
98,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,262,4.087786
104,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,527,4.070209
105,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,257,4.066148
107,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,365,4.032877
110,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,597,4.015075
114,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,296,3.972973
116,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,289,3.972318
122,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,253,3.964427
124,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,292,3.934932
130,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,302,3.927152
138,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,271,3.896679
139,Timeline,MICHAEL CRICHTON,http://images.amazon.com/images/P/0345417623.0...,512,3.857422
146,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,255,3.827451
148,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,252,3.821429
153,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,380,3.818421
155,Angels &amp; Demons,Dan Brown,http://images.amazon.com/images/P/0671027360.0...,616,3.788961
160,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,327,3.785933
161,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,271,3.756458
162,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,413,3.738499
166,Me Talk Pretty One Day,David Sedaris,http://images.amazon.com/images/P/0316776963.0...,426,3.727700
170,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,http://images.amazon.com/images/P/0061009059.0...,269,3.706320
171,Wicked: The Life and Times of the Wicked Witch...,Gregory Maguire,http://images.amazon.com/images/P/0060987103.0...,286,3.678322
172,Bel Canto: A Novel,Ann Patchett,http://images.amazon.com/images/P/0060934417.0...,319,3.664577
173,Confessions of a Shopaholic (Summer Display Op...,SOPHIE KINSELLA,http://images.amazon.com/images/P/0385335482.0...,312,3.663462
174,Misery,Stephen King,http://images.amazon.com/images/P/0451153553.0...,260,3.646154
182,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,455,3.639560
183,Empire Falls,Richard Russo,http://images.amazon.com/images/P/0375726403.0...,368,3.635870

In [ ]:
pickle.dump(pt,open("pt.pkl","wb"))
pickle.dump(books,open("books.pkl","wb"))
pickle.dump(similarity_score,open("similarity_score.pkl","wb"))

In [ ]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...